// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    site_name: "simon@dataeye",
    about_me: "前端开发",
    favicon: "https://cdn1.iconfinder.com/data/icons/bitcoin-casino-coins/32/CoinSphere-Bitcoin-Green-Casino-Chip-32.png",
    posts_path: "posts",
    html_output_path: "html",
    index_page_path: "index.html",
    post_template: "src/template.html",
    index_page_template: "src/index_template.html",
    concurrency: 5,
    default_theme: "darcula",
    stylesheets: [],
    scripts: []
  };

}).call(this);
