// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    site_name: "Simon@coinxu.com",
    about_me: "比特币相关项目创业者",
    posts_path: "posts",
    html_output_path: "html",
    index_page_path: "index.html",
    post_template: "src/template.html",
    index_page_template: "src/index_template.html",
    concurrency: 5,
    default_theme: "darcula",
    stylesheets: [],
    scripts: []
  };

}).call(this);
